書籍一覧作成
CODEBASE-Okinawa/codebase_books_edamame pull request #9
Opened 2023-07-15 08:20 UTC by touyama-yusuke

bookのコントローラー、ルート、一覧画面を作成しました。

2023-07-15 08:28 UTC, osatoh requested changes

2023-07-15 08:28 UTC, osatoh commented on app/views/books/index.html.erb
> +<h2>--------------------------------</h2>
インデントつけましょう 🙌
見やすくなって、ミスも減ります 💪
```suggestion
  <h2>--------------------------------</h2>
    <h2><%= book['title'] %></h2>
    <p>書籍詳細へ</p>
  <h2>--------------------------------</h2>
```

2023-07-15 08:28 UTC, osatoh commented on db/seeds.rb
素敵です :🌊

2023-07-15 09:08 UTC, osatoh commented on config/routes.rb
> +  get 'books/index'
`3000/books`
のようなroutingの方が適切かと思うので修正お願いします 🙏

```
resource :basket, only: [:show, :update, :destroy]
```
こんな感じでかけるので、今はindexアクションのみが必要なことを考慮して変更してみてください 🙌

[Rails のルーティング - Railsガイド](https://railsguides.jp/routing.html#rails%E3%83%AB%E3%83%BC%E3%82%BF%E3%83%BC%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%99%E3%82%8B)

2023-07-15 11:03 UTC, osatoh requested changes

2023-07-15 11:03 UTC, osatoh commented on app/controllers/books_controller.rb
> +    @lending = Lending.all
allで複数取っているので 🙆‍♂️ 
```suggestion
    @books = Book.all
    @reservations = Reservation.all
    @lendings = Lending.all
```

2023-07-15 11:03 UTC, osatoh commented on app/views/books/index.html.erb
> +        <% if @reservation.any?{|reservation| reservation.user_id == session[:user]["id"] }%>
過去に予約した本も条件にひっかかってしまいそうです 👀

2023-07-15 11:03 UTC, osatoh commented on app/views/books/index.html.erb
> +          <% elsif @lending.any?{|lending| lending.user_id == session[:user]["id"] }%>
過去に借りた本も条件に当てはまってしまいそうです 👀

2023-07-15 11:03 UTC, osatoh commented on app/views/books/index.html.erb
> +          <% elsif @lending.any?{|lending| lending.start_date >= Date.today && lending.end_date <= Date.today  }%>
条件式の等式が逆かもしれません 🤔 
```rb
irb(main):005:0> start_date = Date.new(2023,6,10)
=> #<Date: 2023-06-10 ((2460106j,0s,0n),+0s,2299161j)>
irb(main):006:0> start_date >= Date.today
=> false
```

2023-07-15 11:20 UTC, touyama-yusuke commented
コントローラーの変数を複数形に変更、条件式修正してみました。
ご確認お願いいたします。

2023-07-15 11:31 UTC, osatoh requested changes

2023-07-15 11:31 UTC, osatoh commented on app/views/books/index.html.erb
> +        <% if @reservations.any?{|reservation| reservation.user_id == session[:user]["id"] && reservation.end_date >= Date.today }%>
今後借りるものも入ってしまいそうです 👀 
```suggestion
        <% if @reservations.any?{|reservation| reservation.user_id == session[:user]["id"] && reservation.start_date <= Date.today && reservation.end_date >= Date.today }%>
```

2023-07-15 11:31 UTC, osatoh commented on app/views/books/index.html.erb
> +          <% elsif @lendings.any?{|lending| lending.user_id == session[:user]["id"] && lending.start_date <= Date.today && lending.end_date >= Date.today}%>
予約より借りる方が条件式の上に来た方がよさそうです 🤔 
(予約せず借りることはないため、借りてても予約で表示されてしまいそう)

2023-07-16 01:12 UTC, touyama-yusuke commented
条件式変更、画像の挿入追加、カード型でのHTMLに変更してみました。

2023-07-16 01:25 UTC, osatoh commented on Gemfile.lock
> +   2.4.10
```
bundler -v
```
でbunlder のバージョンを確認したのち、 `2.4.10` であれば
```
gem update bundler
```
を実行して再度
```
bundle install
```
を行って欲しいです 🙏

bundlerのバージョンが少し古そうなので 🙆‍♂️

2023-07-16 01:26 UTC, osatoh commented
> カード型でのHTMLに変更してみました。

画面のスクショ欲しいです 🙏

2023-07-16 02:38 UTC, touyama-yusuke commented
<img width="1440" alt="スクリーンショット 2023-07-16 11 36 06" src="https://github.com/CODEBASE-Okinawa/codebase_books_edamame/assets/139226190/906bdb5f-c42e-4b66-b499-fa672da802d9">
<img width="1440" alt="スクリーンショット 2023-07-16 11 36 24" src="https://github.com/CODEBASE-Okinawa/codebase_books_edamame/assets/139226190/ba9be63c-ea75-4685-a19a-1ecf1c7bccf3">

見た目はあんまり変わってないですが、、、

2023-07-16 02:38 UTC, touyama-yusuke commented on Gemfile.lock
> +   2.4.10
かしこまりました！

2023-07-16 02:44 UTC, osatoh requested changes
レビューしました 🙌

2023-07-16 02:44 UTC, osatoh commented on app/views/books/index.html.erb
> +  </a>
全体的にインデント深いので修正お願いします 🙏

2023-07-16 02:45 UTC, touyama-yusuke commented
画像の保存場所をpublicに移動したら表示ができました。

2023-07-16 03:02 UTC, osatoh approved these changes
LGTM 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

2023-07-16 03:02 UTC, merged